name: flutter_movies_app_mohamedhedi_magherbi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  cloud_firestore: ^5.6.0
  curved_labeled_navigation_bar: ^2.0.5
  image_picker: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/google.png
    - images/default_profile.jpg