// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBueJkyAnH79GSsYa78gyQOhyFDvwmIKjQ',
    appId: '1:476417239157:web:76f81a3b552e4b09f1f03c',
    messagingSenderId: '476417239157',
    projectId: 'movies-7ba24',
    authDomain: 'movies-7ba24.firebaseapp.com',
    storageBucket: 'movies-7ba24.firebasestorage.app',
    measurementId: 'G-JY0JE3SS5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaQPvH-Rxi8Mz_shnRpjwmH675pAv6H5s',
    appId: '1:476417239157:android:5c24368ba0fe18b0f1f03c',
    messagingSenderId: '476417239157',
    projectId: 'movies-7ba24',
    storageBucket: 'movies-7ba24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbMYME14XEOQR_rAIJTc8vdbWnx36t_zA',
    appId: '1:476417239157:ios:60cc53684d67f42df1f03c',
    messagingSenderId: '476417239157',
    projectId: 'movies-7ba24',
    storageBucket: 'movies-7ba24.firebasestorage.app',
    iosClientId: '476417239157-2ejl38ilo8m2lvlf455c0cmrg2d9tltn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMoviesAppMohamedhediMagherbi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbMYME14XEOQR_rAIJTc8vdbWnx36t_zA',
    appId: '1:476417239157:ios:60cc53684d67f42df1f03c',
    messagingSenderId: '476417239157',
    projectId: 'movies-7ba24',
    storageBucket: 'movies-7ba24.firebasestorage.app',
    iosClientId: '476417239157-2ejl38ilo8m2lvlf455c0cmrg2d9tltn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMoviesAppMohamedhediMagherbi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBueJkyAnH79GSsYa78gyQOhyFDvwmIKjQ',
    appId: '1:476417239157:web:f52f83e5fcef0a3ef1f03c',
    messagingSenderId: '476417239157',
    projectId: 'movies-7ba24',
    authDomain: 'movies-7ba24.firebaseapp.com',
    storageBucket: 'movies-7ba24.firebasestorage.app',
    measurementId: 'G-JX4NG28X29',
  );

}